<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE annuaire [
    <!ELEMENT annuaire (pole1+)>

    <!ELEMENT pole1 (intitule, fax?, contact*, pole2*)>
    <!ELEMENT pole2 (intitule, fax?, contact*)>
    
    <!ELEMENT intitule (#PCDATA)>
    <!ELEMENT fax (#PCDATA)>
    
    <!ELEMENT personne (nom, prenom)>
    <!ELEMENT nom (#PCDATA)>
    <!ELEMENT prenom (#PCDATA)>
    
    <!ELEMENT contact (poste?, personne+, fixe?, portable?)>
    <!ELEMENT fixe (#PCDATA)>
    <!ELEMENT portable (#PCDATA)>
    <!ELEMENT poste (#PCDATA)>
]>

<annuaire>
    
    <pole1>
        <intitule>Elus municipaux</intitule>
        <contact>
            <poste>Maire</poste>
            <personne>
                <nom>CAP</nom>
                <prenom>Dominique</prenom>
            </personne>
            <fixe>765</fixe>
        </contact>
        <contact>
            <poste>Directeur de cabinet</poste>
            <personne>
                <nom>LE ROUX</nom>
                <prenom>Allain</prenom>
            </personne>
            <fixe>789</fixe>
        </contact>
    </pole1>
    
    <pole1>
        <intitule>Adjoints et conseillers délégués</intitule>
        <contact>
            <personne>
                <nom>HENAFF</nom>
                <prenom>Patricia</prenom>
            </personne>
            <fixe>767</fixe>
        </contact>
        <contact>
            <personne>
                <nom>NICOLAS</nom>
                <prenom>Bernard</prenom>
            </personne>
            <fixe>716</fixe>
        </contact>
        <contact>
            <personne>
                <nom>TOULLEC</nom>
                <prenom>J.-P.</prenom>
            </personne>
            <personne>
                <nom>de CADENET</nom>
                <prenom>B</prenom>
            </personne>
            <fixe>702</fixe>
        </contact>
        <contact>
            <personne>
                <nom>PAUGAM</nom>
                <prenom>Michel</prenom>
            </personne>
            <personne>
                <nom>ANDRE</nom>
                <prenom>J.J.</prenom>
            </personne>
            <fixe>773</fixe>
        </contact>
        <contact>
            <personne>
                <nom>CORRE</nom>
                <prenom>M.</prenom>
            </personne>
            <personne>
                <nom>BATHANY</nom>
                <prenom>N.</prenom>
            </personne>
            <personne>
                <nom>MORVAN</nom>
                <prenom>F.</prenom>
            </personne>
            <fixe>774</fixe>
        </contact>
        <contact>
            <personne>
                <nom>GOUENNOU</nom>
                <prenom>G.</prenom>
            </personne>
            <personne>
                <nom>JEULAND</nom>
                <prenom>P.</prenom>
            </personne>
            <personne>
                <nom>LOUEDEC</nom>
                <prenom>F.</prenom>
            </personne>
            <fixe>134</fixe>
        </contact>
    </pole1>
    
    <pole1>
        <intitule>Pôle Direction Générale</intitule>
        <contact>
            <poste>Directeur Général</poste>
            <personne>
                <nom>LANDRY</nom>
                <prenom>Philippe</prenom>
            </personne>
            <fixe>763</fixe>
            <portable>06 65 11 87 29</portable>
        </contact>
        <pole2>
            <intitule>Secrétariat Général - Légalité</intitule>
            <fax>02 98 37 57 50</fax>
            <contact>
                <personne>
                    <nom>MARTIN</nom>
                    <prenom>Véronique</prenom>
                </personne>
                <fixe>747</fixe>
            </contact>
            <contact>
                <personne>
                    <nom>SEBILLE</nom>
                    <prenom>Stéphanie</prenom>
                </personne>
                <fixe>764</fixe>
            </contact>
        </pole2>
        <pole2>
            <intitule>Police municipale</intitule>
            <contact>
                <personne>
                    <nom>MAUGUEN</nom>
                    <prenom>Rolland</prenom>
                </personne>
                <fixe>755</fixe>
                <portabe>06 08 99 75 52</portabe>
            </contact>
        </pole2>
        <pole2>
            <intitule>Pôle Ressources Humaines</intitule>
            <contact>
                <poste>Directrice</poste>
                <personne>
                    <nom>MALLEGOL</nom>
                    <prenom>Marlène</prenom>
                </personne>
                <fixe>791</fixe>
            </contact>
            <contact>
                <personne>
                    <nom>SALAUN</nom>
                    <prenom>Agnès</prenom>
                </personne>
                <fixe>775</fixe>
            </contact>
            <contact>
                <personne>
                    <nom>LEGRAND</nom>
                    <prenom>Alexandre</prenom>
                </personne>
                <fixe>796</fixe>
            </contact>
        </pole2>
    </pole1>
    
    <pole1>
        <intitule>Pôle Finances Administration Générale</intitule>
        <contact>
            <poste>Directrice</poste>
            <personne>
                <nom>QUENTEL</nom>
                <prenom>Anne</prenom>
            </personne>
            <fixe>785</fixe>
        </contact>
    </pole1>
    
</annuaire>
